# Generated by Django 3.0 on 2021-02-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
    ]
