# Generated by Django 3.0 on 2021-05-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210222_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder_folder_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ManyToManyField(to='main.Folder')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder', to='main.Folder')),
            ],
        ),
    ]
